title: StackAnvil
description: Play on Bedrock servers from Minecraft Java Edition with ViaProxy or the ViaFabricPlus Bedrock add-on.
url: https://stackanvil.pistonmaster.net
baseurl: ""
repository: StackAnvil/patches
theme: just-the-docs
color_scheme: stackanvil
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: true
  focus_shortcut_key: k
enable_copy_code_button: true
back_to_top: true
back_to_top_text: Back to top
callouts:
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: yellow
heading_anchors: true
permalink: pretty
favicon_ico: /assets/images/favicon.svg
aux_links:
  CurseForge:
    - https://www.curseforge.com/minecraft/mc-mods/stackanvil-bedrock-addon-for-viafabricplus
  GitHub:
    - https://github.com/StackAnvil/patches
  Discord:
    - https://discord.gg/F4ZyEtXXge
aux_links_new_tab: true
gh_edit_link: true
gh_edit_link_text: Improve this page
gh_edit_repository: https://github.com/StackAnvil/patches
gh_edit_branch: main
gh_edit_source: site
gh_edit_view_mode: edit
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
